spring:
  application:
#    name: qiyu-live-living-provider --todo 待修改
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://192.168.149.134:8808/qiyu_live_living?useUnicode=true&characterEncoding=utf8
#    数据库name可能修改
    username: root
    password: root
  data:
    redis:
      port: 6379
      host: 192.168.149.134
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
qiyu:
  rmq:
    consumer:
      nameSrv: 192.168.149.134:9876
      groupName: ${spring.application.name}
    producer:
      nameSrv: 192.168.149.134:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 3

#rmq可能不需要
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.149.134:8848?username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9089
    #port: todo 待修改