server:
  port:8084
spring:
  application:
    name: qiyu-live-account-provider
  data:
    redis:
      port: 6379
      host: 192.168.149.134
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: qiyu-live-account-provider
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://192.168.149.134:8848?username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9093
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500